# FinTel v2 - Easy Agent Configuration Demo
# This file demonstrates how simple it is to configure and swap agents

# =============================================================================
# BASIC AGENT CONFIGURATION
# =============================================================================

agents:
  # Financial Analysis Specialist
  FinancialAnalyst:
    name: "FinancialAnalyst"
    description: "Expert financial analyst for comprehensive market analysis"
    # Easy to swap models and providers
    provider: "openai"  # Can easily change to "google" or "local"
    model: "gpt-4o-mini"  # Can change to any supported model
    temperature: 0.1
    max_tokens: 2000
    
    # Core instructions that define the agent's behavior
    instructions: |
      You are a Financial Analyst with expertise in:
      - Market data analysis and interpretation
      - Company fundamentals and financial metrics
      - Investment recommendation synthesis
      - Risk assessment and portfolio management
      
      CORE CAPABILITIES:
      - Extract stock tickers from natural language queries
      - Analyze market data using available tools
      - Provide clear, actionable investment recommendations
      - Synthesize multiple data sources into coherent analysis
      
      TOOL USAGE:
      - Use detect_stock_ticker() to extract ticker symbols
      - Use get_market_data() for current market information
      - Use get_company_overview() for fundamental analysis
      - Use get_economic_data_from_fred() for macro insights
      
      COMMUNICATION STYLE:
      - Professional and data-driven
      - Clear explanations with supporting evidence
      - Balanced perspective considering multiple factors
      - Specific recommendations with confidence levels
    
    # Tools this agent can use (easily swappable)
    tools:
      - "detect_stock_ticker"
      - "get_market_data"
      - "get_company_overview"
      - "get_economic_data_from_fred"
      - "calculate_pe_ratio"
    
    # Specialist capabilities
    capabilities:
      - "stock_analysis"
      - "financial_modeling"
      - "investment_recommendations"
    
    # Easy feature toggles
    settings:
      enabled: true
      max_retries: 3
      timeout: 30
      fallback_agent: "MarketAnalyst"

  # Market Analysis Specialist  
  MarketAnalyst:
    name: "MarketAnalyst"
    description: "Specialized in market data analysis and technical indicators"
    provider: "openai"
    model: "gpt-4o-mini"
    temperature: 0.1
    max_tokens: 1500
    
    instructions: |
      You are a Market Analyst specializing in:
      - Real-time market data interpretation
      - Technical analysis and price patterns
      - Market sentiment analysis
      - Trading volume and liquidity assessment
      
      FOCUS AREAS:
      - Current stock prices and movements
      - Market trends and momentum
      - Volume analysis and liquidity
      - Short-term market dynamics
      
      APPROACH:
      - Gather current market data using tools
      - Analyze price movements and trends
      - Assess market conditions and sentiment
      - Provide technical perspective on investment timing
    
    tools:
      - "get_market_data"
      - "get_company_overview"
    
    capabilities:
      - "market_data_analysis"
      - "technical_analysis"
      - "sentiment_analysis"
    
    settings:
      enabled: true
      max_retries: 2
      timeout: 25
      fallback_agent: "FinancialAnalyst"

  # Economic Analysis Specialist
  EconomicAnalyst:
    name: "EconomicAnalyst"  
    description: "Expert in macroeconomic trends and their market impact"
    provider: "openai"
    model: "gpt-4o-mini"
    temperature: 0.1
    max_tokens: 1500
    
    instructions: |
      You are an Economic Analyst focused on:
      - Macroeconomic trends and indicators
      - Federal Reserve policy impacts
      - Economic data interpretation
      - Sector-wide economic influences
      
      EXPERTISE:
      - GDP, inflation, and employment data
      - Interest rates and monetary policy
      - Economic cycles and market timing
      - Sector rotation and economic sensitivity
      
      METHODOLOGY:
      - Analyze relevant economic indicators
      - Assess policy impacts on markets
      - Provide macroeconomic context for investments
      - Identify economic risks and opportunities
    
    tools:
      - "get_economic_data_from_fred"
    
    capabilities:
      - "macroeconomic_analysis"
      - "policy_analysis"
      - "economic_forecasting"
    
    settings:
      enabled: true
      max_retries: 2
      timeout: 25
      fallback_agent: "FinancialAnalyst"

  # Risk Assessment Specialist
  RiskAssessment:
    name: "RiskAssessment"
    description: "Specialized in investment risk analysis and portfolio management"
    provider: "openai" 
    model: "gpt-4o-mini"
    temperature: 0.1
    max_tokens: 1500
    
    instructions: |
      You are a Risk Assessment Specialist with expertise in:
      - Investment risk quantification
      - Portfolio risk management
      - Volatility and correlation analysis
      - Risk-adjusted return metrics
      
      RISK CATEGORIES:
      - Market risk (systematic risk)
      - Company-specific risk (unsystematic risk)  
      - Liquidity risk and trading considerations
      - Sector and geographic concentration risks
      
      ANALYSIS FRAMEWORK:
      - Quantify risk levels (Low/Medium/High)
      - Identify key risk factors
      - Assess risk-return trade-offs
      - Provide risk mitigation recommendations
    
    tools:
      - "get_market_data"
      - "get_company_overview"
    
    capabilities:
      - "risk_assessment"
      - "portfolio_analysis"
      - "volatility_analysis"
    
    settings:
      enabled: true
      max_retries: 2
      timeout: 25
      fallback_agent: "FinancialAnalyst"

# =============================================================================
# AGENT TEAM CONFIGURATIONS
# =============================================================================

# Define different agent teams for different analysis types
teams:
  comprehensive_analysis:
    name: "Comprehensive Financial Analysis Team"
    description: "Full-spectrum analysis using all specialists"
    agents:
      - "FinancialAnalyst"    # Coordinator and synthesizer
      - "MarketAnalyst"       # Market data specialist
      - "EconomicAnalyst"     # Macro specialist  
      - "RiskAssessment"      # Risk specialist
    coordination: "FinancialAnalyst"  # Lead coordinator

  quick_market_check:
    name: "Quick Market Analysis Team"
    description: "Fast market assessment for time-sensitive decisions"
    agents:
      - "MarketAnalyst"
      - "FinancialAnalyst"
    coordination: "MarketAnalyst"

  risk_focused:
    name: "Risk-Focused Analysis Team"
    description: "Deep dive into investment risks and portfolio impact"
    agents:
      - "RiskAssessment"
      - "FinancialAnalyst"
    coordination: "RiskAssessment"

# =============================================================================
# EASY CUSTOMIZATION EXAMPLES
# =============================================================================

# Want to use Google's Gemini instead? Just change:
# provider: "google"
# model: "gemini-1.5-flash"

# Want to use a local model? Just change:
# provider: "local"
# model: "local-model"

# Want to add a new specialist? Just add:
# TechnicalAnalyst:
#   name: "TechnicalAnalyst"
#   provider: "openai"
#   model: "gpt-4o-mini"
#   instructions: "You are a technical analysis expert..."
#   tools: ["get_market_data"]
#   capabilities: ["chart_analysis", "pattern_recognition"]

# Want to disable an agent temporarily? Just change:
# settings:
#   enabled: false

# Want to swap tools? Just modify the tools list:
# tools:
#   - "new_tool_name"
#   - "another_tool"