# Unified Tool Configuration - Single Source of Truth
# This file defines all available tools in the system with their metadata and dependencies

tools:
  # Market Data Tools
  get_market_data:
    name: "get_market_data"
    description: "Get real-time market data for a stock ticker"
    category: "market_data"
    function: "get_market_data"
    class: "MarketDataTool"
    api_key_required: "alpha_vantage"
    enabled: true
    examples:
      - "get_market_data(ticker='AAPL')"
      - "get_market_data(ticker='GOOG')"
    
  get_company_overview:
    name: "get_company_overview"
    description: "Get comprehensive company overview and fundamental data"
    category: "market_data"
    function: "get_company_overview"
    class: "CompanyOverviewTool"
    api_key_required: "alpha_vantage"
    enabled: true
    examples:
      - "get_company_overview(ticker='AAPL')"
      - "get_company_overview(ticker='MSFT')"
    
  # Economic Data Tools
  get_economic_data_from_fred:
    name: "get_economic_data_from_fred"
    description: "Get economic data from FRED (Federal Reserve Economic Data)"
    category: "economic_data"
    function: "get_economic_data_from_fred"
    class: "EconomicDataTool"
    api_key_required: "fred"
    enabled: true
    examples:
      - "get_economic_data_from_fred(series_id='GDP')"
      - "get_economic_data_from_fred(series_id='UNRATE', limit=20)"
    
  # Utility Tools
  detect_stock_ticker:
    name: "detect_stock_ticker"
    description: "AI-powered stock ticker detection from natural language queries"
    category: "utility"
    function: "detect_stock_ticker"
    class: null
    api_key_required: null
    enabled: true
    examples:
      - "detect_stock_ticker(query='analyze Apple stock')"
      - "detect_stock_ticker(query='what is happening with TSLA')"
    
  process_strict_json:
    name: "process_strict_json"
    description: "Process a dictionary of financial data with strict JSON validation"
    category: "utility"
    function: "process_strict_json"
    class: null
    api_key_required: null
    enabled: true
    examples:
      - "process_strict_json(data={'asset': 'BTC', 'value': 70000})"
    
  # Validation Tools
  process_financial_data:
    name: "process_financial_data"
    description: "Validate and ensure data quality for financial analysis"
    category: "validation"
    function: "process_financial_data"
    class: null
    api_key_required: null
    enabled: true
    examples:
      - "process_financial_data(data={'price': 150.25, 'volume': 1234567})"
    
  misleading_data_validator:
    name: "misleading_data_validator"
    description: "Validate financial data with advanced format checking"
    category: "validation"
    function: "misleading_data_validator"
    class: null
    api_key_required: null
    enabled: true
    examples:
      - "misleading_data_validator(data={'ticker': 'AAPL', 'price': 185.50})"
    
  # Analysis Tools
  calculate_pe_ratio:
    name: "calculate_pe_ratio"
    description: "Calculate P/E ratio for a given stock and compare it to industry averages"
    category: "analysis"
    function: "calculate_pe_ratio"
    class: null
    api_key_required: null
    enabled: true
    examples:
      - "calculate_pe_ratio(ticker='AAPL')"
      - "calculate_pe_ratio(ticker='GOOG', current_price=150.0)"
    
  analyze_cash_flow:
    name: "analyze_cash_flow"
    description: "Analyze cash flow for a company and identify trends and financial health indicators"
    category: "analysis"
    function: "analyze_cash_flow"
    class: null
    api_key_required: null
    enabled: true
    examples:
      - "analyze_cash_flow(ticker='AAPL')"
      - "analyze_cash_flow(ticker='MSFT', period='annual')"
    
  get_competitor_analysis:
    name: "get_competitor_analysis"
    description: "Compare company against competitors and analyze competitive positioning"
    category: "analysis"
    function: "get_competitor_analysis"
    class: null
    api_key_required: null
    enabled: true
    examples:
      - "get_competitor_analysis(ticker='AAPL')"
      - "get_competitor_analysis(ticker='GOOG', competitors=['MSFT', 'AMZN'])"

  # Alpha Vantage Time Series & Indicators
  get_time_series_daily:
    name: "get_time_series_daily"
    description: "Get daily time series (adjusted/raw) from Alpha Vantage"
    category: "market_data"
    function: "get_time_series_daily"
    class: null
    api_key_required: "alpha_vantage"
    enabled: true
    examples:
      - "get_time_series_daily(ticker='VSCO', outputsize='compact', adjusted=true)"

  get_time_series_intraday:
    name: "get_time_series_intraday"
    description: "Get intraday time series from Alpha Vantage"
    category: "market_data"
    function: "get_time_series_intraday"
    class: null
    api_key_required: "alpha_vantage"
    enabled: true
    examples:
      - "get_time_series_intraday(ticker='VSCO', interval='5min', outputsize='compact')"

  get_rsi:
    name: "get_rsi"
    description: "Get RSI indicator from Alpha Vantage"
    category: "analysis"
    function: "get_rsi"
    class: null
    api_key_required: "alpha_vantage"
    enabled: true
    examples:
      - "get_rsi(ticker='VSCO', interval='daily', time_period=14, series_type='close')"

  get_macd:
    name: "get_macd"
    description: "Get MACD indicator from Alpha Vantage"
    category: "analysis"
    function: "get_macd"
    class: null
    api_key_required: "alpha_vantage"
    enabled: true
    examples:
      - "get_macd(ticker='VSCO', interval='daily', series_type='close')"

  # Fundamental statements
  get_income_statement:
    name: "get_income_statement"
    description: "Get income statement fundamentals from Alpha Vantage"
    category: "analysis"
    function: "get_income_statement"
    class: null
    api_key_required: "alpha_vantage"
    enabled: true
    examples:
      - "get_income_statement(ticker='VSCO')"

  get_balance_sheet:
    name: "get_balance_sheet"
    description: "Get balance sheet fundamentals from Alpha Vantage"
    category: "analysis"
    function: "get_balance_sheet"
    class: null
    api_key_required: "alpha_vantage"
    enabled: true
    examples:
      - "get_balance_sheet(ticker='VSCO')"

  get_cash_flow:
    name: "get_cash_flow"
    description: "Get cash flow fundamentals from Alpha Vantage"
    category: "analysis"
    function: "get_cash_flow"
    class: null
    api_key_required: "alpha_vantage"
    enabled: true
    examples:
      - "get_cash_flow(ticker='VSCO')"

  # Demo/Mock Tools
  get_mock_news:
    name: "get_mock_news"
    description: "Return recent mock headlines for a ticker (demo)"
    category: "analysis"
    function: "get_mock_news"
    class: null
    api_key_required: null
    enabled: false
    examples:
      - "get_mock_news(ticker='AAPL', limit=3)"

  get_mock_analyst_ratings:
    name: "get_mock_analyst_ratings"
    description: "Return mock analyst ratings (demo)"
    category: "analysis"
    function: "get_mock_analyst_ratings"
    class: null
    api_key_required: null
    enabled: false
    examples:
      - "get_mock_analyst_ratings(ticker='AAPL')"

  get_mock_social_sentiment:
    name: "get_mock_social_sentiment"
    description: "Return mock social sentiment metrics (demo)"
    category: "analysis"
    function: "get_mock_social_sentiment"
    class: null
    api_key_required: null
    enabled: false
    examples:
      - "get_mock_social_sentiment(ticker='AAPL')"

  # Alpha Intelligence tools
  get_news_sentiment:
    name: "get_news_sentiment"
    description: "Fetch news and sentiment from Alpha Vantage Alpha Intelligence"
    category: "analysis"
    function: "get_news_sentiment"
    class: null
    api_key_required: "alpha_vantage"
    enabled: true
    examples:
      - "get_news_sentiment(ticker='AAPL', limit=50)"

  get_earnings_transcript:
    name: "get_earnings_transcript"
    description: "Fetch earnings call transcript for a specific quarter/year"
    category: "analysis"
    function: "get_earnings_transcript"
    class: null
    api_key_required: "alpha_vantage"
    enabled: true
    examples:
      - "get_earnings_transcript(ticker='AAPL', quarter=3, year=2024)"

  get_top_gainers_losers:
    name: "get_top_gainers_losers"
    description: "Fetch top gainers, losers, and most active tickers"
    category: "market_data"
    function: "get_top_gainers_losers"
    class: null
    api_key_required: "alpha_vantage"
    enabled: true
    examples:
      - "get_top_gainers_losers()"

  get_insider_transactions:
    name: "get_insider_transactions"
    description: "Fetch recent insider transactions for a ticker"
    category: "analysis"
    function: "get_insider_transactions"
    class: null
    api_key_required: "alpha_vantage"
    enabled: true
    examples:
      - "get_insider_transactions(ticker='AAPL', limit=50)"

  get_alpha_analytics:
    name: "get_alpha_analytics"
    description: "Fetch Alpha Vantage analytics (fixed/sliding window) for a ticker"
    category: "analysis"
    function: "get_alpha_analytics"
    class: null
    api_key_required: "alpha_vantage"
    enabled: true
    examples:
      - "get_alpha_analytics(ticker='AAPL', window='fixed', horizon='30d')"

  build_features:
    name: "build_features"
    description: "Compose engineered features from time series, news, insiders, fundamentals, and breadth"
    category: "analysis"
    function: "build_features"
    class: null
    api_key_required: null
    enabled: true
    examples:
      - "build_features(ticker='AAPL', time_series_daily={...}, news={...}, insiders={...})"

  train_model:
    name: "train_model"
    description: "Train the baseline classification model on labeled records"
    category: "analysis"
    function: "train_model"
    class: null
    api_key_required: null
    enabled: true
    examples:
      - "train_model(records=[{features: {ret_1d: 0.01, ...}, label: 1}], calibrate=true)"

  predict_from_features:
    name: "predict_from_features"
    description: "Predict probability of upward move from engineered features"
    category: "analysis"
    function: "predict_from_features"
    class: null
    api_key_required: null
    enabled: true
    examples:
      - "predict_from_features(features={ret_1d: 0.01, ...})"

  backtest_baseline:
    name: "backtest_baseline"
    description: "Walk-forward backtest with baseline model using price-derived features"
    category: "analysis"
    function: "backtest_baseline"
    class: null
    api_key_required: null
    enabled: true
    examples:
      - "backtest_baseline(ticker='AAPL', daily_series={...}, horizon_days=10)"

# Tool Categories
categories:
  market_data:
    name: "Market Data"
    description: "Tools for fetching real-time market data and company information"
    
  economic_data:
    name: "Economic Data"
    description: "Tools for accessing macroeconomic indicators and economic data"
    
  utility:
    name: "Utility"
    description: "General utility tools for data processing and analysis"
    
  validation:
    name: "Validation"
    description: "Tools for validating and ensuring data quality"
    
  analysis:
    name: "Analysis"
    description: "Tools for performing financial analysis and calculations"

# API Key Requirements
api_keys:
  alpha_vantage:
    name: "Alpha Vantage"
    description: "Required for market data and company overview tools"
    env_var: "ALPHA_VANTAGE_API_KEY"
    
  fred:
    name: "FRED"
    description: "Required for economic data tools"
    env_var: "FRED_API_KEY"
    
  openai:
    name: "OpenAI"
    description: "Required for AI-powered tools and agents"
    env_var: "OPENAI_API_KEY"
    
  google:
    name: "Google"
    description: "Alternative AI provider"
    env_var: "GOOGLE_API_KEY" 