#
# Fintel v2 - Universal Workflow Configuration
#
# This file is the single source of truth for defining analytical workflows.
# Each workflow assembles a team of specialist agents from agents.yaml
# to achieve a specific financial analysis goal.
#

workflows:
  # WORKFLOW 1: Quick, high-level analysis of a single stock.
  quick_stock_analysis:
    name: "Quick Stock Analysis"
    description: "Fast, high-level analysis of a specific stock for a go/no-go investment decision."
    agents:
      - name: "MarketAnalyst"
        role: "market_analysis"
        required: true
        fallback: "FinancialAnalyst"
        tools: [
          "get_market_data",
          "get_company_overview",
          "get_mock_news",
          "get_mock_analyst_ratings",
          "get_mock_social_sentiment"
        ]
      - name: "RiskAssessment"
        role: "risk_assessment"
        required: true
        fallback: "FinancialAnalyst"
        tools: [
          "get_market_data",
          "get_mock_analyst_ratings",
          "get_mock_social_sentiment"
        ]
      - name: "Summarizer"
        role: "synthesis"
        required: true
        fallback: "FinancialAnalyst"
        tools: []
        dependencies: ["market_analysis", "risk_assessment"]

  # WORKFLOW 2: Deep dive into a company's competitive landscape.
  competitor_deep_dive:
    name: "Sector & Competitor Deep Dive"
    description: "Analyzes a company's position within its sector by comparing it against key competitors."
    agents:
      - name: "MarketAnalyst"
        role: "primary_company_analysis"
        required: true
        tools: ["get_company_overview", "get_competitor_analysis"]
      - name: "FinancialAnalyst"
        role: "competitor_comparison"
        required: true
        tools: ["get_market_data", "calculate_pe_ratio"]
      - name: "Summarizer"
        role: "strategic_summary"
        required: true
        tools: []
        dependencies: ["primary_company_analysis", "competitor_comparison"]

  # WORKFLOW 3: High-level analysis of broad economic trends.
  macroeconomic_outlook:
    name: "Macroeconomic Outlook"
    description: "Assesses the overall economic climate using key indicators like GDP, inflation, and unemployment."
    agents:
      - name: "EconomicAnalyst"
        role: "economic_data_analysis"
        required: true
        tools: ["get_economic_data_from_fred"]
      - name: "RiskAssessment"
        role: "macro_risk_assessment"
        required: false
        fallback: "EconomicAnalyst"
        tools: ["get_economic_data_from_fred"]
      - name: "Summarizer"
        role: "economic_summary"
        required: true
        tools: []
        dependencies: ["economic_data_analysis", "macro_risk_assessment"]

# --- Global Settings ---
settings:
  default_workflow: "quick_stock_analysis"
  enable_fallback_agents: true
  log_agent_availability: true