# FinTel v2 - Easy Workflow Configuration Demo
# This file shows how simple it is to configure different workflow patterns

# =============================================================================
# WORKFLOW CONFIGURATION EXAMPLES
# =============================================================================

workflows:
  # Standard comprehensive analysis workflow
  comprehensive_analysis:
    name: "Comprehensive Financial Analysis"
    description: "Full-spectrum analysis using all available specialists"
    
    # Define the workflow steps and agent assignments
    steps:
      - step: "ticker_extraction"
        agent: "FinancialAnalyst"
        task: "Extract stock ticker from user query"
        tools: ["detect_stock_ticker"]
        required: true
        
      - step: "market_analysis" 
        agent: "MarketAnalyst"
        task: "Analyze current market data and trends"
        tools: ["get_market_data", "get_company_overview"]
        depends_on: ["ticker_extraction"]
        required: true
        fallback: "FinancialAnalyst"
        
      - step: "economic_context"
        agent: "EconomicAnalyst"
        task: "Provide macroeconomic context and trends"
        tools: ["get_economic_data_from_fred"]
        depends_on: ["ticker_extraction"]
        required: false  # Optional step
        fallback: "FinancialAnalyst"
        
      - step: "risk_assessment"
        agent: "RiskAssessment"
        task: "Assess investment risks and volatility"
        tools: ["get_market_data", "get_company_overview"]
        depends_on: ["market_analysis"]
        required: true
        fallback: "FinancialAnalyst"
        
      - step: "final_synthesis"
        agent: "FinancialAnalyst"
        task: "Synthesize all analysis into investment recommendation"
        tools: ["get_market_data", "get_company_overview"]
        depends_on: ["market_analysis", "risk_assessment"]
        required: true
    
    # Workflow settings
    settings:
      max_execution_time: 120  # seconds
      parallel_execution: true  # Run independent steps in parallel
      retry_failed_steps: true
      max_retries: 2

  # Quick analysis for time-sensitive decisions
  quick_analysis:
    name: "Quick Market Check"
    description: "Fast analysis for urgent investment decisions"
    
    steps:
      - step: "ticker_extraction"
        agent: "FinancialAnalyst"
        task: "Extract ticker from query"
        tools: ["detect_stock_ticker"]
        required: true
        
      - step: "market_snapshot"
        agent: "MarketAnalyst"
        task: "Get current market data and basic analysis"
        tools: ["get_market_data", "get_company_overview"]
        depends_on: ["ticker_extraction"]
        required: true
        
      - step: "quick_recommendation"
        agent: "FinancialAnalyst"
        task: "Provide quick investment recommendation"
        tools: ["get_market_data"]
        depends_on: ["market_snapshot"]
        required: true
    
    settings:
      max_execution_time: 30  # Fast execution
      parallel_execution: false
      retry_failed_steps: false

  # Risk-focused analysis workflow
  risk_focused:
    name: "Risk-Focused Analysis"
    description: "Deep dive into investment risks and portfolio impact"
    
    steps:
      - step: "ticker_extraction"
        agent: "FinancialAnalyst"
        task: "Extract ticker from query"
        tools: ["detect_stock_ticker"]
        required: true
        
      - step: "market_data_collection"
        agent: "MarketAnalyst"
        task: "Gather comprehensive market data"
        tools: ["get_market_data", "get_company_overview"]
        depends_on: ["ticker_extraction"]
        required: true
        
      - step: "detailed_risk_analysis"
        agent: "RiskAssessment"
        task: "Perform detailed risk assessment"
        tools: ["get_market_data", "get_company_overview"]
        depends_on: ["market_data_collection"]
        required: true
        
      - step: "risk_synthesis"
        agent: "FinancialAnalyst"
        task: "Synthesize risk findings with recommendations"
        tools: []
        depends_on: ["detailed_risk_analysis"]
        required: true
    
    settings:
      max_execution_time: 90
      parallel_execution: true
      retry_failed_steps: true
      max_retries: 1

# =============================================================================
# DYNAMIC WORKFLOW SELECTION
# =============================================================================

# Automatically select workflow based on query keywords
workflow_selection:
  rules:
    - keywords: ["quick", "fast", "urgent", "now"]
      workflow: "quick_analysis"
      
    - keywords: ["risk", "volatile", "safe", "dangerous"]
      workflow: "risk_focused"
      
    - keywords: ["comprehensive", "detailed", "full", "complete"]
      workflow: "comprehensive_analysis"
      
    # Default fallback
    - default: "comprehensive_analysis"

# =============================================================================
# EASY CUSTOMIZATION EXAMPLES
# =============================================================================

# Want to create a new workflow? Just add:
# custom_workflow:
#   name: "My Custom Analysis"
#   description: "Tailored for specific needs"
#   steps:
#     - step: "my_step"
#       agent: "FinancialAnalyst"
#       task: "Do something specific"
#       tools: ["some_tool"]
#       required: true

# Want to disable economic analysis? Just change:
# - step: "economic_context"
#   required: false  # or remove the step entirely

# Want to change the order? Just reorder the steps:
# The workflow engine will respect the depends_on relationships

# Want to use different agents? Just change:
# agent: "MyNewAgent"  # (assuming you've configured it in agents.yaml)

# Want to add parallel processing? Just change:
# settings:
#   parallel_execution: true

# Want faster execution? Just change:
# settings:
#   max_execution_time: 15  # seconds
#   retry_failed_steps: false