import React from 'react';

const ReportHeader: React.FC = () => (
  <div className="text-center">
    <h2 className="text-3xl font-bold text-white">Financial Intelligence Report</h2>
    <p className="text-brand-text-secondary mt-1">Generated by FINTEL Multi-Agent System</p>
  </div>
);

export default ReportHeader;